### ISSUE TITLE
onClickCell events are not working on fixed columns

### ISSUE THREAD

**Issue by anjareddy** [wenzhixin/bootstrap-table-fixed-columns#18]
http://jsfiddle.net/anjrddygddm/e3nk137y/11552/
onClickCell event is not working if a column is fixed.
Need a solution.

**Comment by brunotnt** [comment]
Hi @anjareddy  @wenzhixin 
There was a bug that did not trigger the click on fixed column cells.
This is due to the fact that when fixing a column a copy of the table is made with only the fixed columns and it overlaps the original table.
To solve I captured the click of the fixed cell and triggered via jQuery the click event of the corresponding original cell.

see on my fork. 
https://github.com/brunotnt/bootstrap-table-fixed-columns/commit/6c502e2c16d6c63958da28960dbbf9cba0051805

**Comment by wenzhixin** [comment]
This extension has moved to [bootstrap-table](https://github.com/wenzhixin/bootstrap-table), the issue has been fixed.
* https://bootstrap-table.com/docs/extensions/fixed-columns/
* https://examples.bootstrap-table.com/#extensions/fixed-columns.html
